[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
BenchmarkCI = "20533458-34a3-403d-a444-e18f38190b5b"
PkgBenchmark = "32113eaa-f34f-5b0d-bd6c-c81e245fc73d"

[compat]
BenchmarkCI = "0.1.9"
BenchmarkTools = "1.6.3"
PkgBenchmark = "0.2.15"
