name = "PeriodicInterpolation1D"
uuid = "d32cb302-a956-591b-8d53-254f0a948d40"
version = "0.1.0"
authors = ["Katharina Kormann <k.kormann@rub.de>", " Pierre Navaro <navaro@math.cnrs.fr>", " Klaus Reuter <khr@mpcdf.mpg.de> "]

[workspace]
projects = ["test", "docs", "benchmark"]

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FastInterpolations = "9ea80cae-fc13-4c00-8066-6eaedb12f34b"

[compat]
DocStringExtensions = "0.9.5"
FFTW = "1.10.0"
FastInterpolations = "0.2.13"
julia = "1.10"
