name = "LagrangeInterpolation1D"
uuid = "d32cb302-a956-591b-8d53-254f0a948d40"
version = "0.1.0"
authors = ["Katharina Kormann <k.kormann@rub.de>", " Pierre Navaro <navaro@math.cnrs.fr>", " Klaus Reuter <khr@mpcdf.mpg.de> "]

[workspace]
projects = ["test", "docs", "benchmark"]

[deps]
BenchmarkCI = "20533458-34a3-403d-a444-e18f38190b5b"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
PkgBenchmark = "32113eaa-f34f-5b0d-bd6c-c81e245fc73d"

[compat]
BenchmarkCI = "0.1.9"
BenchmarkTools = "1.6.3"
PkgBenchmark = "0.2.15"
julia = "1.10"
