[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LiveServer = "16fef848-5104-11e9-1b77-fb7a48bbb589"
LagrangeInterpolation1D = "d32cb302-a956-591b-8d53-254f0a948d40"

[compat]
Documenter = "1"

[sources]
LagrangeInterpolation1D = {path = ".."}
